"""Defaults for the isolated Goal-conditioned SAC experiment."""

GOAL_SAC_BATCH_SIZE = 1024
GOAL_SAC_BUFFER_SIZE = 500_000
GOAL_SAC_LEARNING_STARTS = 50_000
GOAL_SAC_LEARNING_RATE = 3e-4
GOAL_SAC_TRAIN_FREQ = 1
GOAL_SAC_TAU = 0.005
GOAL_SAC_GAMMA = 0.99
GOAL_SAC_ENT_COEF = "auto"
GOAL_SAC_N_ENVS = 64
GOAL_SAC_EPOCHS = 100
GOAL_SAC_EPISODES_PER_EPOCH = 100
GOAL_SAC_MAX_EPISODE_STEPS = 2048

GOAL_SAC_HER_RATIO = 0.50
GOAL_SAC_HER_SAFE_MARGIN_M = 0.0005
GOAL_SAC_GOAL_TOLERANCE = 0.01
GOAL_SAC_CRITIC_ENSEMBLE_SIZE = 10
GOAL_SAC_TARGET_CRITIC_SUBSET_SIZE = 2
GOAL_SAC_UTD_RATIO = 10
GOAL_SAC_UTD_WARMUP_STEPS = 50_000
GOAL_SAC_ACTOR_UPDATE_INTERVAL = 2
GOAL_SAC_CRITIC_LAYER_NORM = True
